# Copyright © 2025 ANSYS, Inc. Unauthorized use, distribution, or duplication is prohibited. 
################################################################################
#
# ModelCenter Remote Execution Source Code
#
# Copyright © 2025 ANSYS, Inc.
#
# DO NOT EDIT THIS FILE.
#
################################################################################
clientFaker = "None"
